[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

[build]
  publish = "dist/payment-managing-app/browser"
  command = "ng build --configuration production"

[[plugins]]
package = "@netlify/angular-runtime"